name: Continuous Delivery

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.15.0"
          cache: "npm"
      - name: Install dependencies for the twilio plugin
        run: |
          npm install
      - name: Deploying to Twilio
        run: |
          npm run ci:deploy-flows --if-present
          #npm run ci:deploy-functions --if-present
        env:
          ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
